apiVersion: 1

prune: false

datasources:
  - name: AInterview Prometheus
    uid: ainterview-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.55.1
