import { Activity, ArrowUpRight, CircleAlert, Database, ExternalLink, Gauge, History, RefreshCw, Server, ShieldCheck, TriangleAlert, Wifi } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { request } from '@/lib/api'
import type { AdminOperationsSummary } from '@/lib/admin'

function tone(state: string): 'success' | 'danger' | 'warning' | 'info' | 'default' { return state === 'UP' ? 'success' : state === 'DOWN' ? 'danger' : state === 'ATTENTION' ? 'warning' : 'default' }
function icon(code: string) { return code === 'mysql' ? <Database className="h-5 w-5" /> : code === 'redis' ? <Wifi className="h-5 w-5" /> : code.includes('task') || code.includes('backlog') ? <Activity className="h-5 w-5" /> : code === 'backend' || code.includes('gateway') || code.includes('registry') || code.includes('worker') ? <Server className="h-5 w-5" /> : <Gauge className="h-5 w-5" /> }

export function AdminOperations() {
  const [data, setData] = useState<AdminOperationsSummary | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await request<AdminOperationsSummary>('/v1/admin/operations/summary')) } catch (reason) { setError(reason instanceof Error ? reason.message : '系统健康摘要加载失败，请稍后重试。') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const components = data?.components ?? []
  const attention = components.filter(item => item.state === 'ATTENTION' || item.state === 'DOWN')
  return <div className="space-y-6"><header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-[var(--accent)]">运维摘要</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">运行健康</h1><p className="mt-3 max-w-3xl text-muted-foreground">只在业务后台显示脱敏状态和处理建议；详细指标、趋势与告警继续交给 Grafana。</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" className="h-10" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />刷新健康</Button><a href={data?.metricsPath ?? '/grafana/'} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[var(--accent)] px-4 text-sm font-semibold text-white transition hover:opacity-90"><ExternalLink className="h-4 w-4" />{data?.metricsLabel ?? '打开 Grafana'}</a></div></header>{error && <Card className="border-[var(--danger)]/30 bg-[var(--danger)]/5 text-sm text-[var(--danger)]">{error}</Card>}
    <section className="grid gap-4 md:grid-cols-3"><Card><p className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="h-4 w-4" />健康组件</p><strong className="mt-3 block text-3xl">{loading ? '…' : components.filter(item => item.state === 'UP').length}/{components.length}</strong><p className="mt-2 text-xs text-muted-foreground">服务端摘要，不展示内部连接信息</p></Card><Card><p className="flex items-center gap-2 text-sm text-muted-foreground"><TriangleAlert className="h-4 w-4" />需要关注</p><strong className="mt-3 block text-3xl">{loading ? '…' : attention.length}</strong><p className="mt-2 text-xs text-muted-foreground">按建议逐项处理</p></Card><Card><p className="flex items-center gap-2 text-sm text-muted-foreground"><History className="h-4 w-4" />最近更新时间</p><strong className="mt-3 block text-lg sm:text-2xl">{loading || !data ? '…' : new Date(data.generatedAt).toLocaleString('zh-CN', { hour12: false })}</strong><p className="mt-2 text-xs text-muted-foreground">业务时间来自后端</p></Card></section>
    {attention.length > 0 && <Card className="border-[var(--warning)]/35 bg-[var(--warning)]/5"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-[var(--warning-foreground)]" /><div><h2 className="font-bold">处理建议</h2><div className="mt-3 grid gap-2 text-sm">{attention.map(item => <p key={item.code}><strong>{item.label}：</strong>{item.recommendation}</p>)}</div></div></div></Card>}
    <section><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">System health</p><h2 className="mt-2 text-xl font-bold">服务与依赖</h2></div><span className="text-xs text-muted-foreground">仅显示状态摘要</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{components.map(item => <Card key={item.code} className="min-w-0 p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]">{icon(item.code)}</span><h3 className="break-words font-bold">{item.label}</h3></div><Badge tone={tone(item.state)}>{item.stateLabel}</Badge></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{item.summary}</p><div className="mt-4 border-t border-border pt-4 text-xs leading-5 text-muted-foreground"><strong className="text-foreground">建议：</strong>{item.recommendation}</div></Card>)}</div>{!loading && !components.length && <Card className="mt-4 text-sm text-muted-foreground">暂无健康摘要。</Card>}</section>
    <Card><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Next step</p><h2 className="mt-2 text-xl font-bold">需要深入查看时</h2><p className="mt-2 text-sm text-muted-foreground">健康页不承载日志和配置操作，避免把诊断信息与业务操作混在一起。</p></div><div className="flex flex-wrap gap-2"><Link to="/admin/ai-operations" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[var(--accent)] px-4 text-sm font-semibold text-white">查看 AI 中心<ArrowUpRight className="h-4 w-4" /></Link><Link to="/admin/audit-logs" className="inline-flex h-10 items-center gap-2 rounded-xl border border-border px-4 text-sm font-semibold transition hover:bg-muted"><History className="h-4 w-4" />查看操作审计</Link></div></div></Card>
  </div>
}
